// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by ProductPaletteFactory.GeneratePrecompiledPalettesCode()
// Generated on: 2025-12-24 23:49:26 UTC

#nullable enable

using System;
using System.Collections.Generic;

namespace Flowery.Theming
{
    /// <summary>
    /// Pre-compiled product theme palettes. No runtime conversion needed.
    /// </summary>
    public static class ProductPalettes
    {
        private static readonly Dictionary<string, ThemePalette> Palettes = new(StringComparer.OrdinalIgnoreCase)
        {
            ["SaaS"] = new ThemePalette
            {
                Primary = "#2563EB", PrimaryFocus = "#1D4FBC", PrimaryContent = "#FFFFFF",
                Secondary = "#3B82F6", SecondaryFocus = "#2F68C4", SecondaryContent = "#FFFFFF",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MicroSaaS"] = new ThemePalette
            {
                Primary = "#6366F1", PrimaryFocus = "#4F51C0", PrimaryContent = "#FFFFFF",
                Secondary = "#818CF8", SecondaryFocus = "#6770C6", SecondaryContent = "#000000",
                Accent = "#10B981", AccentFocus = "#0C9467", AccentContent = "#000000",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Ecommerce"] = new ThemePalette
            {
                Primary = "#3B82F6", PrimaryFocus = "#2F68C4", PrimaryContent = "#FFFFFF",
                Secondary = "#60A5FA", SecondaryFocus = "#4C84C8", SecondaryContent = "#000000",
                Accent = "#16A34A", AccentFocus = "#11823B", AccentContent = "#FFFFFF",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["EcommerceLuxury"] = new ThemePalette
            {
                Primary = "#1C1917", PrimaryFocus = "#161412", PrimaryContent = "#FFFFFF",
                Secondary = "#44403C", SecondaryFocus = "#363330", SecondaryContent = "#FFFFFF",
                Accent = "#CA8A04", AccentFocus = "#A16E03", AccentContent = "#000000",
                Neutral = "#0A0908", NeutralFocus = "#090807", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAF9", Base200 = "#EDEDEC", Base300 = "#D6D3D1", BaseContent = "#0C0A09",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["ServiceLanding"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#38BDF8", SecondaryFocus = "#2C97C6", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["B2BService"] = new ThemePalette
            {
                Primary = "#0F172A", PrimaryFocus = "#0C1221", PrimaryContent = "#FFFFFF",
                Secondary = "#334155", SecondaryFocus = "#283444", SecondaryContent = "#FFFFFF",
                Accent = "#0369A1", AccentFocus = "#025480", AccentContent = "#FFFFFF",
                Neutral = "#010514", NeutralFocus = "#010412", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#020617",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["FinancialDashboard"] = new ThemePalette
            {
                Primary = "#1E3A5F", PrimaryFocus = "#182E4C", PrimaryContent = "#FFFFFF",
                Secondary = "#2563EB", SecondaryFocus = "#1D4FBC", SecondaryContent = "#FFFFFF",
                Accent = "#DC2626", AccentFocus = "#B01E1E", AccentContent = "#FFFFFF",
                Neutral = "#D8DCE0", NeutralFocus = "#C0C4C7", NeutralContent = "#000000",
                Base100 = "#0F172A", Base200 = "#1B2234", Base300 = "#334155", BaseContent = "#F1F5F9",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["AnalyticsDashboard"] = new ThemePalette
            {
                Primary = "#6366F1", PrimaryFocus = "#4F51C0", PrimaryContent = "#FFFFFF",
                Secondary = "#8B5CF6", SecondaryFocus = "#6F49C4", SecondaryContent = "#FFFFFF",
                Accent = "#F59E0B", AccentFocus = "#C47E08", AccentContent = "#000000",
                Neutral = "#E0E1E1", NeutralFocus = "#C7C8C8", NeutralContent = "#000000",
                Base100 = "#111827", Base200 = "#1C2331", Base300 = "#374151", BaseContent = "#F9FAFB",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["HealthcareApp"] = new ThemePalette
            {
                Primary = "#0891B2", PrimaryFocus = "#06748E", PrimaryContent = "#FFFFFF",
                Secondary = "#22D3EE", SecondaryFocus = "#1BA8BE", SecondaryContent = "#000000",
                Accent = "#059669", AccentFocus = "#047854", AccentContent = "#FFFFFF",
                Neutral = "#134659", NeutralFocus = "#113E4F", NeutralContent = "#FFFFFF",
                Base100 = "#ECFEFF", Base200 = "#E0F1F2", Base300 = "#A5F3FC", BaseContent = "#164E63",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["EducationalApp"] = new ThemePalette
            {
                Primary = "#4F46E5", PrimaryFocus = "#3F38B7", PrimaryContent = "#FFFFFF",
                Secondary = "#818CF8", SecondaryFocus = "#6770C6", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#1B1843", NeutralFocus = "#18153C", NeutralContent = "#FFFFFF",
                Base100 = "#EEF2FF", Base200 = "#E2E5F2", Base300 = "#C7D2FE", BaseContent = "#1E1B4B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["CreativeAgency"] = new ThemePalette
            {
                Primary = "#EC4899", PrimaryFocus = "#BC397A", PrimaryContent = "#000000",
                Secondary = "#F472B6", SecondaryFocus = "#C35B91", SecondaryContent = "#000000",
                Accent = "#06B6D4", AccentFocus = "#0491A9", AccentContent = "#000000",
                Neutral = "#75153C", NeutralFocus = "#681335", NeutralContent = "#FFFFFF",
                Base100 = "#FDF2F8", Base200 = "#F0E5EB", Base300 = "#FBCFE8", BaseContent = "#831843",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Portfolio"] = new ThemePalette
            {
                Primary = "#18181B", PrimaryFocus = "#131315", PrimaryContent = "#FFFFFF",
                Secondary = "#3F3F46", SecondaryFocus = "#323238", SecondaryContent = "#FFFFFF",
                Accent = "#2563EB", AccentFocus = "#1D4FBC", AccentContent = "#FFFFFF",
                Neutral = "#080809", NeutralFocus = "#070708", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAFA", Base200 = "#EDEDED", Base300 = "#E4E4E7", BaseContent = "#09090B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Gaming"] = new ThemePalette
            {
                Primary = "#7C3AED", PrimaryFocus = "#632EBD", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#F43F5E", AccentFocus = "#C3324B", AccentContent = "#FFFFFF",
                Neutral = "#CBD0D8", NeutralFocus = "#B4B9C0", NeutralContent = "#000000",
                Base100 = "#0F0F23", Base200 = "#1B1B2E", Base300 = "#4C1D95", BaseContent = "#E2E8F0",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["Government"] = new ThemePalette
            {
                Primary = "#0F172A", PrimaryFocus = "#0C1221", PrimaryContent = "#FFFFFF",
                Secondary = "#334155", SecondaryFocus = "#283444", SecondaryContent = "#FFFFFF",
                Accent = "#0369A1", AccentFocus = "#025480", AccentContent = "#FFFFFF",
                Neutral = "#010514", NeutralFocus = "#010412", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#020617",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["FintechCrypto"] = new ThemePalette
            {
                Primary = "#F59E0B", PrimaryFocus = "#C47E08", PrimaryContent = "#000000",
                Secondary = "#FBBF24", SecondaryFocus = "#C8981C", SecondaryContent = "#000000",
                Accent = "#8B5CF6", AccentFocus = "#6F49C4", AccentContent = "#FFFFFF",
                Neutral = "#DFE1E2", NeutralFocus = "#C6C8C9", NeutralContent = "#000000",
                Base100 = "#0F172A", Base200 = "#1B2234", Base300 = "#334155", BaseContent = "#F8FAFC",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["SocialMedia"] = new ThemePalette
            {
                Primary = "#2563EB", PrimaryFocus = "#1D4FBC", PrimaryContent = "#FFFFFF",
                Secondary = "#60A5FA", SecondaryFocus = "#4C84C8", SecondaryContent = "#000000",
                Accent = "#F43F5E", AccentFocus = "#C3324B", AccentContent = "#FFFFFF",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#DBEAFE", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["ProductivityTool"] = new ThemePalette
            {
                Primary = "#059669", PrimaryFocus = "#047854", PrimaryContent = "#FFFFFF",
                Secondary = "#34D399", SecondaryFocus = "#29A87A", SecondaryContent = "#000000",
                Accent = "#2563EB", AccentFocus = "#1D4FBC", AccentContent = "#FFFFFF",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#D1FAE5", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["DesignSystem"] = new ThemePalette
            {
                Primary = "#7C3AED", PrimaryFocus = "#632EBD", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#F472B6", AccentFocus = "#C35B91", AccentContent = "#000000",
                Neutral = "#1B2431", NeutralFocus = "#18202C", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAFA", Base200 = "#EDEDED", Base300 = "#E5E7EB", BaseContent = "#1F2937",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["AIChatbot"] = new ThemePalette
            {
                Primary = "#7C3AED", PrimaryFocus = "#632EBD", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#06B6D4", AccentFocus = "#0491A9", AccentContent = "#000000",
                Neutral = "#1B1843", NeutralFocus = "#18153C", NeutralContent = "#FFFFFF",
                Base100 = "#FAF5FF", Base200 = "#EDE8F2", Base300 = "#DDD6FE", BaseContent = "#1E1B4B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["NFTWeb3"] = new ThemePalette
            {
                Primary = "#8B5CF6", PrimaryFocus = "#6F49C4", PrimaryContent = "#FFFFFF",
                Secondary = "#C4B5FD", SecondaryFocus = "#9C90CA", SecondaryContent = "#000000",
                Accent = "#FFD700", AccentFocus = "#CCAC00", AccentContent = "#000000",
                Neutral = "#DFE1E2", NeutralFocus = "#C6C8C9", NeutralContent = "#000000",
                Base100 = "#0F0F23", Base200 = "#1B1B2E", Base300 = "#4C1D95", BaseContent = "#F8FAFC",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["CreatorEconomy"] = new ThemePalette
            {
                Primary = "#EC4899", PrimaryFocus = "#BC397A", PrimaryContent = "#000000",
                Secondary = "#F9A8D4", SecondaryFocus = "#C786A9", SecondaryContent = "#000000",
                Accent = "#8B5CF6", AccentFocus = "#6F49C4", AccentContent = "#FFFFFF",
                Neutral = "#75153C", NeutralFocus = "#681335", NeutralContent = "#FFFFFF",
                Base100 = "#FDF2F8", Base200 = "#F0E5EB", Base300 = "#FBCFE8", BaseContent = "#831843",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SustainabilityESG"] = new ThemePalette
            {
                Primary = "#228B22", PrimaryFocus = "#1B6F1B", PrimaryContent = "#FFFFFF",
                Secondary = "#4ADE80", SecondaryFocus = "#3BB166", SecondaryContent = "#000000",
                Accent = "#92400E", AccentFocus = "#74330B", AccentContent = "#FFFFFF",
                Neutral = "#124A28", NeutralFocus = "#104224", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDF4", Base200 = "#E4F0E7", Base300 = "#BBF7D0", BaseContent = "#14532D",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["RemoteWork"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#7DD3FC", SecondaryFocus = "#64A8C9", SecondaryContent = "#000000",
                Accent = "#F59E0B", AccentFocus = "#C47E08", AccentContent = "#000000",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F0F9FF", Base200 = "#E4ECF2", Base300 = "#BAE6FD", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MentalHealth"] = new ThemePalette
            {
                Primary = "#8B5CF6", PrimaryFocus = "#6F49C4", PrimaryContent = "#FFFFFF",
                Secondary = "#C4B5FD", SecondaryFocus = "#9C90CA", SecondaryContent = "#000000",
                Accent = "#14B8A6", AccentFocus = "#109384", AccentContent = "#000000",
                Neutral = "#441A86", NeutralFocus = "#3C1777", NeutralContent = "#FFFFFF",
                Base100 = "#FAF5FF", Base200 = "#EDE8F2", Base300 = "#DDD6FE", BaseContent = "#4C1D95",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["PetTech"] = new ThemePalette
            {
                Primary = "#F97316", PrimaryFocus = "#C75C11", PrimaryContent = "#000000",
                Secondary = "#FDBA74", SecondaryFocus = "#CA945C", SecondaryContent = "#000000",
                Accent = "#84CC16", AccentFocus = "#69A311", AccentContent = "#000000",
                Neutral = "#8A2E10", NeutralFocus = "#7B290E", NeutralContent = "#FFFFFF",
                Base100 = "#FFF7ED", Base200 = "#F2EAE1", Base300 = "#FED7AA", BaseContent = "#9A3412",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SmartHomeIoT"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#38BDF8", SecondaryFocus = "#2C97C6", SecondaryContent = "#000000",
                Accent = "#22C55E", AccentFocus = "#1B9D4B", AccentContent = "#000000",
                Neutral = "#D8DCE0", NeutralFocus = "#C0C4C7", NeutralContent = "#000000",
                Base100 = "#0F172A", Base200 = "#1B2234", Base300 = "#334155", BaseContent = "#F1F5F9",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["EVCharging"] = new ThemePalette
            {
                Primary = "#009CD1", PrimaryFocus = "#007CA7", PrimaryContent = "#FFFFFF",
                Secondary = "#22D3EE", SecondaryFocus = "#1BA8BE", SecondaryContent = "#000000",
                Accent = "#22C55E", AccentFocus = "#1B9D4B", AccentContent = "#000000",
                Neutral = "#114642", NeutralFocus = "#0F3E3B", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDFA", Base200 = "#E4F0ED", Base300 = "#99F6E4", BaseContent = "#134E4A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SubscriptionBox"] = new ThemePalette
            {
                Primary = "#E11D48", PrimaryFocus = "#B41739", PrimaryContent = "#FFFFFF",
                Secondary = "#FB7185", SecondaryFocus = "#C85A6A", SecondaryContent = "#000000",
                Accent = "#8B5CF6", AccentFocus = "#6F49C4", AccentContent = "#FFFFFF",
                Neutral = "#7A1131", NeutralFocus = "#6C0F2C", NeutralContent = "#FFFFFF",
                Base100 = "#FFF1F2", Base200 = "#F2E4E5", Base300 = "#FECDD3", BaseContent = "#881337",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Podcast"] = new ThemePalette
            {
                Primary = "#7C3AED", PrimaryFocus = "#632EBD", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#F472B6", AccentFocus = "#C35B91", AccentContent = "#000000",
                Neutral = "#D8DCE0", NeutralFocus = "#C0C4C7", NeutralContent = "#000000",
                Base100 = "#0F0F23", Base200 = "#1B1B2E", Base300 = "#4C1D95", BaseContent = "#F1F5F9",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["Dating"] = new ThemePalette
            {
                Primary = "#E11D48", PrimaryFocus = "#B41739", PrimaryContent = "#FFFFFF",
                Secondary = "#FB7185", SecondaryFocus = "#C85A6A", SecondaryContent = "#000000",
                Accent = "#F472B6", AccentFocus = "#C35B91", AccentContent = "#000000",
                Neutral = "#7A1131", NeutralFocus = "#6C0F2C", NeutralContent = "#FFFFFF",
                Base100 = "#FFF1F2", Base200 = "#F2E4E5", Base300 = "#FECDD3", BaseContent = "#881337",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MicroCredentials"] = new ThemePalette
            {
                Primary = "#2563EB", PrimaryFocus = "#1D4FBC", PrimaryContent = "#FFFFFF",
                Secondary = "#60A5FA", SecondaryFocus = "#4C84C8", SecondaryContent = "#000000",
                Accent = "#FFD700", AccentFocus = "#CCAC00", AccentContent = "#000000",
                Neutral = "#1B399D", NeutralFocus = "#18338C", NeutralContent = "#FFFFFF",
                Base100 = "#EFF6FF", Base200 = "#E3E9F2", Base300 = "#BFDBFE", BaseContent = "#1E40AF",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["KnowledgeBase"] = new ThemePalette
            {
                Primary = "#374151", PrimaryFocus = "#2C3440", PrimaryContent = "#FFFFFF",
                Secondary = "#6B7280", SecondaryFocus = "#555B66", SecondaryContent = "#FFFFFF",
                Accent = "#3B82F6", AccentFocus = "#2F68C4", AccentContent = "#FFFFFF",
                Neutral = "#0F1523", NeutralFocus = "#0D131F", NeutralContent = "#FFFFFF",
                Base100 = "#F9FAFB", Base200 = "#ECEDEE", Base300 = "#E5E7EB", BaseContent = "#111827",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["HyperlocalServices"] = new ThemePalette
            {
                Primary = "#DC2626", PrimaryFocus = "#B01E1E", PrimaryContent = "#FFFFFF",
                Secondary = "#F87171", SecondaryFocus = "#C65A5A", SecondaryContent = "#000000",
                Accent = "#2563EB", AccentFocus = "#1D4FBC", AccentContent = "#FFFFFF",
                Neutral = "#891818", NeutralFocus = "#7A1515", NeutralContent = "#FFFFFF",
                Base100 = "#FEF2F2", Base200 = "#F1E5E5", Base300 = "#FECACA", BaseContent = "#991B1B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["BeautySpaWellness"] = new ThemePalette
            {
                Primary = "#FFB6C1", PrimaryFocus = "#CC919A", PrimaryContent = "#000000",
                Secondary = "#FECDD3", SecondaryFocus = "#CBA4A8", SecondaryContent = "#000000",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#75153C", NeutralFocus = "#681335", NeutralContent = "#FFFFFF",
                Base100 = "#FFF5F7", Base200 = "#F2E8EA", Base300 = "#FBCFE8", BaseContent = "#831843",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["LuxuryPremium"] = new ThemePalette
            {
                Primary = "#1C1917", PrimaryFocus = "#161412", PrimaryContent = "#FFFFFF",
                Secondary = "#44403C", SecondaryFocus = "#363330", SecondaryContent = "#FFFFFF",
                Accent = "#CA8A04", AccentFocus = "#A16E03", AccentContent = "#000000",
                Neutral = "#0A0908", NeutralFocus = "#090807", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAF9", Base200 = "#EDEDEC", Base300 = "#D6D3D1", BaseContent = "#0C0A09",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["RestaurantFood"] = new ThemePalette
            {
                Primary = "#DC2626", PrimaryFocus = "#B01E1E", PrimaryContent = "#FFFFFF",
                Secondary = "#F87171", SecondaryFocus = "#C65A5A", SecondaryContent = "#000000",
                Accent = "#CA8A04", AccentFocus = "#A16E03", AccentContent = "#000000",
                Neutral = "#3E0909", NeutralFocus = "#370808", NeutralContent = "#FFFFFF",
                Base100 = "#FEF2F2", Base200 = "#F1E5E5", Base300 = "#FECACA", BaseContent = "#450A0A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["FitnessGym"] = new ThemePalette
            {
                Primary = "#FF6B35", PrimaryFocus = "#CC552A", PrimaryContent = "#000000",
                Secondary = "#FB923C", SecondaryFocus = "#C87430", SecondaryContent = "#000000",
                Accent = "#22C55E", AccentFocus = "#1B9D4B", AccentContent = "#000000",
                Neutral = "#E1E1E1", NeutralFocus = "#C8C8C8", NeutralContent = "#000000",
                Base100 = "#18181B", Base200 = "#232326", Base300 = "#3F3F46", BaseContent = "#FAFAFA",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["RealEstate"] = new ThemePalette
            {
                Primary = "#0077B6", PrimaryFocus = "#005F91", PrimaryContent = "#FFFFFF",
                Secondary = "#0EA5E9", SecondaryFocus = "#0B84BA", SecondaryContent = "#000000",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#BAE6FD", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["TravelTourism"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#38BDF8", SecondaryFocus = "#2C97C6", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F0F9FF", Base200 = "#E4ECF2", Base300 = "#BAE6FD", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["HotelHospitality"] = new ThemePalette
            {
                Primary = "#1E3A8A", PrimaryFocus = "#182E6E", PrimaryContent = "#FFFFFF",
                Secondary = "#3B82F6", SecondaryFocus = "#2F68C4", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#1B399D", NeutralFocus = "#18338C", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#BFDBFE", BaseContent = "#1E40AF",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["WeddingEvent"] = new ThemePalette
            {
                Primary = "#FFD6E0", PrimaryFocus = "#CCABB3", PrimaryContent = "#000000",
                Secondary = "#FBCFE8", SecondaryFocus = "#C8A5B9", SecondaryContent = "#000000",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#75153C", NeutralFocus = "#681335", NeutralContent = "#FFFFFF",
                Base100 = "#FFF5F7", Base200 = "#F2E8EA", Base300 = "#F9A8D4", BaseContent = "#831843",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["LegalServices"] = new ThemePalette
            {
                Primary = "#1E3A5F", PrimaryFocus = "#182E4C", PrimaryContent = "#FFFFFF",
                Secondary = "#1E40AF", SecondaryFocus = "#18338C", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#0D1425", NeutralFocus = "#0C1221", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#CBD5E1", BaseContent = "#0F172A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Insurance"] = new ThemePalette
            {
                Primary = "#0066CC", PrimaryFocus = "#0051A3", PrimaryContent = "#FFFFFF",
                Secondary = "#3B82F6", SecondaryFocus = "#2F68C4", SecondaryContent = "#FFFFFF",
                Accent = "#16A34A", AccentFocus = "#11823B", AccentContent = "#FFFFFF",
                Neutral = "#1B3455", NeutralFocus = "#182E4C", NeutralContent = "#FFFFFF",
                Base100 = "#F0F9FF", Base200 = "#E4ECF2", Base300 = "#BFDBFE", BaseContent = "#1E3A5F",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["BankingFinance"] = new ThemePalette
            {
                Primary = "#0A1628", PrimaryFocus = "#081120", PrimaryContent = "#FFFFFF",
                Secondary = "#1E3A8A", SecondaryFocus = "#182E6E", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#0D1425", NeutralFocus = "#0C1221", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#CBD5E1", BaseContent = "#0F172A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["OnlineCourse"] = new ThemePalette
            {
                Primary = "#0D9488", PrimaryFocus = "#0A766C", PrimaryContent = "#FFFFFF",
                Secondary = "#2DD4BF", SecondaryFocus = "#24A998", SecondaryContent = "#000000",
                Accent = "#EA580C", AccentFocus = "#BB4609", AccentContent = "#FFFFFF",
                Neutral = "#114642", NeutralFocus = "#0F3E3B", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDFA", Base200 = "#E4F0ED", Base300 = "#5EEAD4", BaseContent = "#134E4A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["NonProfit"] = new ThemePalette
            {
                Primary = "#0891B2", PrimaryFocus = "#06748E", PrimaryContent = "#FFFFFF",
                Secondary = "#22D3EE", SecondaryFocus = "#1BA8BE", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#134659", NeutralFocus = "#113E4F", NeutralContent = "#FFFFFF",
                Base100 = "#ECFEFF", Base200 = "#E0F1F2", Base300 = "#A5F3FC", BaseContent = "#164E63",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MusicStreaming"] = new ThemePalette
            {
                Primary = "#1DB954", PrimaryFocus = "#179443", PrimaryContent = "#FFFFFF",
                Secondary = "#1ED760", SecondaryFocus = "#18AC4C", SecondaryContent = "#000000",
                Accent = "#FF6B35", AccentFocus = "#CC552A", AccentContent = "#000000",
                Neutral = "#E5E5E5", NeutralFocus = "#CCCCCC", NeutralContent = "#000000",
                Base100 = "#121212", Base200 = "#1D1D1D", Base300 = "#282828", BaseContent = "#FFFFFF",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["VideoStreamingOTT"] = new ThemePalette
            {
                Primary = "#E50914", PrimaryFocus = "#B70710", PrimaryContent = "#FFFFFF",
                Secondary = "#B20710", SecondaryFocus = "#8E050C", SecondaryContent = "#FFFFFF",
                Accent = "#FFFFFF", AccentFocus = "#CCCCCC", AccentContent = "#000000",
                Neutral = "#E5E5E5", NeutralFocus = "#CCCCCC", NeutralContent = "#000000",
                Base100 = "#141414", Base200 = "#1F1F1F", Base300 = "#333333", BaseContent = "#FFFFFF",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["JobBoard"] = new ThemePalette
            {
                Primary = "#0A66C2", PrimaryFocus = "#08519B", PrimaryContent = "#FFFFFF",
                Secondary = "#378FE9", SecondaryFocus = "#2C72BA", SecondaryContent = "#FFFFFF",
                Accent = "#16A34A", AccentFocus = "#11823B", AccentContent = "#FFFFFF",
                Neutral = "#000000", NeutralFocus = "#000000", NeutralContent = "#FFFFFF",
                Base100 = "#F3F2EF", Base200 = "#E6E5E3", Base300 = "#E0DFDC", BaseContent = "#000000",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MarketplaceP2P"] = new ThemePalette
            {
                Primary = "#FF5A5F", PrimaryFocus = "#CC484C", PrimaryContent = "#000000",
                Secondary = "#FF7E82", SecondaryFocus = "#CC6468", SecondaryContent = "#000000",
                Accent = "#00A699", AccentFocus = "#00847A", AccentContent = "#FFFFFF",
                Neutral = "#404040", NeutralFocus = "#393939", NeutralContent = "#FFFFFF",
                Base100 = "#F7F7F7", Base200 = "#EAEAEA", Base300 = "#EBEBEB", BaseContent = "#484848",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["LogisticsDelivery"] = new ThemePalette
            {
                Primary = "#2563EB", PrimaryFocus = "#1D4FBC", PrimaryContent = "#FFFFFF",
                Secondary = "#3B82F6", SecondaryFocus = "#2F68C4", SecondaryContent = "#FFFFFF",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["AgricultureFarm"] = new ThemePalette
            {
                Primary = "#4A7C23", PrimaryFocus = "#3B631C", PrimaryContent = "#FFFFFF",
                Secondary = "#65A30D", SecondaryFocus = "#50820A", SecondaryContent = "#FFFFFF",
                Accent = "#92400E", AccentFocus = "#74330B", AccentContent = "#FFFFFF",
                Neutral = "#304A12", NeutralFocus = "#2B4210", NeutralContent = "#FFFFFF",
                Base100 = "#FEFCE8", Base200 = "#F1EFDC", Base300 = "#D9F99D", BaseContent = "#365314",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Construction"] = new ThemePalette
            {
                Primary = "#4A4A4A", PrimaryFocus = "#3B3B3B", PrimaryContent = "#FFFFFF",
                Secondary = "#6B7280", SecondaryFocus = "#555B66", SecondaryContent = "#FFFFFF",
                Accent = "#FF6B35", AccentFocus = "#CC552A", AccentContent = "#000000",
                Neutral = "#1B2431", NeutralFocus = "#18202C", NeutralContent = "#FFFFFF",
                Base100 = "#F5F5F5", Base200 = "#E8E8E8", Base300 = "#D1D5DB", BaseContent = "#1F2937",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Automotive"] = new ThemePalette
            {
                Primary = "#1C1C1C", PrimaryFocus = "#161616", PrimaryContent = "#FFFFFF",
                Secondary = "#4B5563", SecondaryFocus = "#3C444F", SecondaryContent = "#FFFFFF",
                Accent = "#EF4444", AccentFocus = "#BF3636", AccentContent = "#FFFFFF",
                Neutral = "#0F1523", NeutralFocus = "#0D131F", NeutralContent = "#FFFFFF",
                Base100 = "#F9FAFB", Base200 = "#ECEDEE", Base300 = "#D1D5DB", BaseContent = "#111827",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Photography"] = new ThemePalette
            {
                Primary = "#000000", PrimaryFocus = "#000000", PrimaryContent = "#FFFFFF",
                Secondary = "#374151", SecondaryFocus = "#2C3440", SecondaryContent = "#FFFFFF",
                Accent = "#FAFAFA", AccentFocus = "#C8C8C8", AccentContent = "#000000",
                Neutral = "#000000", NeutralFocus = "#000000", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAFA", Base200 = "#EDEDED", Base300 = "#E5E7EB", BaseContent = "#000000",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Coworking"] = new ThemePalette
            {
                Primary = "#F97316", PrimaryFocus = "#C75C11", PrimaryContent = "#000000",
                Secondary = "#FDBA74", SecondaryFocus = "#CA945C", SecondaryContent = "#000000",
                Accent = "#8B4513", AccentFocus = "#6F370F", AccentContent = "#FFFFFF",
                Neutral = "#6C2F0D", NeutralFocus = "#602A0C", NeutralContent = "#FFFFFF",
                Base100 = "#FFFBEB", Base200 = "#F2EEDF", Base300 = "#FDE68A", BaseContent = "#78350F",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["CleaningService"] = new ThemePalette
            {
                Primary = "#00B4D8", PrimaryFocus = "#0090AC", PrimaryContent = "#000000",
                Secondary = "#48CAE4", SecondaryFocus = "#39A1B6", SecondaryContent = "#000000",
                Accent = "#22C55E", AccentFocus = "#1B9D4B", AccentContent = "#000000",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDFA", Base200 = "#E4F0ED", Base300 = "#99F6E4", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["HomeServices"] = new ThemePalette
            {
                Primary = "#1E3A8A", PrimaryFocus = "#182E6E", PrimaryContent = "#FFFFFF",
                Secondary = "#3B82F6", SecondaryFocus = "#2F68C4", SecondaryContent = "#FFFFFF",
                Accent = "#FF6B35", AccentFocus = "#CC552A", AccentContent = "#000000",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Childcare"] = new ThemePalette
            {
                Primary = "#F472B6", PrimaryFocus = "#C35B91", PrimaryContent = "#000000",
                Secondary = "#FBCFE8", SecondaryFocus = "#C8A5B9", SecondaryContent = "#000000",
                Accent = "#FCD34D", AccentFocus = "#C9A83D", AccentContent = "#000000",
                Neutral = "#75153C", NeutralFocus = "#681335", NeutralContent = "#FFFFFF",
                Base100 = "#FDF2F8", Base200 = "#F0E5EB", Base300 = "#F9A8D4", BaseContent = "#831843",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SeniorCare"] = new ThemePalette
            {
                Primary = "#0891B2", PrimaryFocus = "#06748E", PrimaryContent = "#FFFFFF",
                Secondary = "#67E8F9", SecondaryFocus = "#52B9C7", SecondaryContent = "#000000",
                Accent = "#F59E0B", AccentFocus = "#C47E08", AccentContent = "#000000",
                Neutral = "#134659", NeutralFocus = "#113E4F", NeutralContent = "#FFFFFF",
                Base100 = "#ECFEFF", Base200 = "#E0F1F2", Base300 = "#A5F3FC", BaseContent = "#164E63",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MedicalClinic"] = new ThemePalette
            {
                Primary = "#0077B6", PrimaryFocus = "#005F91", PrimaryContent = "#FFFFFF",
                Secondary = "#48CAE4", SecondaryFocus = "#39A1B6", SecondaryContent = "#000000",
                Accent = "#16A34A", AccentFocus = "#11823B", AccentContent = "#FFFFFF",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F0F9FF", Base200 = "#E4ECF2", Base300 = "#BAE6FD", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Pharmacy"] = new ThemePalette
            {
                Primary = "#22C55E", PrimaryFocus = "#1B9D4B", PrimaryContent = "#000000",
                Secondary = "#4ADE80", SecondaryFocus = "#3BB166", SecondaryContent = "#000000",
                Accent = "#0077B6", AccentFocus = "#005F91", AccentContent = "#FFFFFF",
                Neutral = "#124A28", NeutralFocus = "#104224", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDF4", Base200 = "#E4F0E7", Base300 = "#BBF7D0", BaseContent = "#14532D",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["DentalPractice"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#7DD3FC", SecondaryFocus = "#64A8C9", SecondaryContent = "#000000",
                Accent = "#FCD34D", AccentFocus = "#C9A83D", AccentContent = "#000000",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F0F9FF", Base200 = "#E4ECF2", Base300 = "#BAE6FD", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["VeterinaryClinic"] = new ThemePalette
            {
                Primary = "#0891B2", PrimaryFocus = "#06748E", PrimaryContent = "#FFFFFF",
                Secondary = "#67E8F9", SecondaryFocus = "#52B9C7", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#134659", NeutralFocus = "#113E4F", NeutralContent = "#FFFFFF",
                Base100 = "#ECFEFF", Base200 = "#E0F1F2", Base300 = "#A5F3FC", BaseContent = "#164E63",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["FloristPlant"] = new ThemePalette
            {
                Primary = "#22C55E", PrimaryFocus = "#1B9D4B", PrimaryContent = "#000000",
                Secondary = "#86EFAC", SecondaryFocus = "#6BBF89", SecondaryContent = "#000000",
                Accent = "#EC4899", AccentFocus = "#BC397A", AccentContent = "#000000",
                Neutral = "#124A28", NeutralFocus = "#104224", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDF4", Base200 = "#E4F0E7", Base300 = "#BBF7D0", BaseContent = "#14532D",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["BakeryCafe"] = new ThemePalette
            {
                Primary = "#92400E", PrimaryFocus = "#74330B", PrimaryContent = "#FFFFFF",
                Secondary = "#D97706", SecondaryFocus = "#AD5F04", SecondaryContent = "#000000",
                Accent = "#FCD34D", AccentFocus = "#C9A83D", AccentContent = "#000000",
                Neutral = "#6C2F0D", NeutralFocus = "#602A0C", NeutralContent = "#FFFFFF",
                Base100 = "#FFFBEB", Base200 = "#F2EEDF", Base300 = "#FDE68A", BaseContent = "#78350F",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["CoffeeShop"] = new ThemePalette
            {
                Primary = "#6F4E37", PrimaryFocus = "#583E2C", PrimaryContent = "#FFFFFF",
                Secondary = "#A78B71", SecondaryFocus = "#856F5A", SecondaryContent = "#000000",
                Accent = "#D4A574", AccentFocus = "#A9845C", AccentContent = "#000000",
                Neutral = "#362412", NeutralFocus = "#302010", NeutralContent = "#FFFFFF",
                Base100 = "#FEF7ED", Base200 = "#F1EAE1", Base300 = "#E8DDD4", BaseContent = "#3D2914",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["BreweryWinery"] = new ThemePalette
            {
                Primary = "#7C2D12", PrimaryFocus = "#63240E", PrimaryContent = "#FFFFFF",
                Secondary = "#C2410C", SecondaryFocus = "#9B3409", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#3E0909", NeutralFocus = "#370808", NeutralContent = "#FFFFFF",
                Base100 = "#FEF2F2", Base200 = "#F1E5E5", Base300 = "#FCA5A5", BaseContent = "#450A0A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Airline"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#7DD3FC", SecondaryFocus = "#64A8C9", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#0A4263", NeutralFocus = "#093B58", NeutralContent = "#FFFFFF",
                Base100 = "#F0F9FF", Base200 = "#E4ECF2", Base300 = "#BAE6FD", BaseContent = "#0C4A6E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["NewsMedia"] = new ThemePalette
            {
                Primary = "#18181B", PrimaryFocus = "#131315", PrimaryContent = "#FFFFFF",
                Secondary = "#3F3F46", SecondaryFocus = "#323238", SecondaryContent = "#FFFFFF",
                Accent = "#DC2626", AccentFocus = "#B01E1E", AccentContent = "#FFFFFF",
                Neutral = "#080809", NeutralFocus = "#070708", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAFA", Base200 = "#EDEDED", Base300 = "#E4E4E7", BaseContent = "#09090B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MagazineBlog"] = new ThemePalette
            {
                Primary = "#EC4899", PrimaryFocus = "#BC397A", PrimaryContent = "#000000",
                Secondary = "#F9A8D4", SecondaryFocus = "#C786A9", SecondaryContent = "#000000",
                Accent = "#000000", AccentFocus = "#000000", AccentContent = "#FFFFFF",
                Neutral = "#151518", NeutralFocus = "#131315", NeutralContent = "#FFFFFF",
                Base100 = "#FFFFFF", Base200 = "#F2F2F2", Base300 = "#F3F4F6", BaseContent = "#18181B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Freelancer"] = new ThemePalette
            {
                Primary = "#059669", PrimaryFocus = "#047854", PrimaryContent = "#FFFFFF",
                Secondary = "#34D399", SecondaryFocus = "#29A87A", SecondaryContent = "#000000",
                Accent = "#2563EB", AccentFocus = "#1D4FBC", AccentContent = "#FFFFFF",
                Neutral = "#010514", NeutralFocus = "#010412", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#020617",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Consulting"] = new ThemePalette
            {
                Primary = "#0F172A", PrimaryFocus = "#0C1221", PrimaryContent = "#FFFFFF",
                Secondary = "#334155", SecondaryFocus = "#283444", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#010514", NeutralFocus = "#010412", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#020617",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MarketingAgency"] = new ThemePalette
            {
                Primary = "#EC4899", PrimaryFocus = "#BC397A", PrimaryContent = "#000000",
                Secondary = "#F472B6", SecondaryFocus = "#C35B91", SecondaryContent = "#000000",
                Accent = "#06B6D4", AccentFocus = "#0491A9", AccentContent = "#000000",
                Neutral = "#75153C", NeutralFocus = "#681335", NeutralContent = "#FFFFFF",
                Base100 = "#FDF2F8", Base200 = "#F0E5EB", Base300 = "#FBCFE8", BaseContent = "#831843",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["EventManagement"] = new ThemePalette
            {
                Primary = "#7C3AED", PrimaryFocus = "#632EBD", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#441A86", NeutralFocus = "#3C1777", NeutralContent = "#FFFFFF",
                Base100 = "#FAF5FF", Base200 = "#EDE8F2", Base300 = "#DDD6FE", BaseContent = "#4C1D95",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["ConferenceWebinar"] = new ThemePalette
            {
                Primary = "#0F172A", PrimaryFocus = "#0C1221", PrimaryContent = "#FFFFFF",
                Secondary = "#334155", SecondaryFocus = "#283444", SecondaryContent = "#FFFFFF",
                Accent = "#0369A1", AccentFocus = "#025480", AccentContent = "#FFFFFF",
                Neutral = "#010514", NeutralFocus = "#010412", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#020617",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MembershipCommunity"] = new ThemePalette
            {
                Primary = "#7C3AED", PrimaryFocus = "#632EBD", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#F97316", AccentFocus = "#C75C11", AccentContent = "#000000",
                Neutral = "#441A86", NeutralFocus = "#3C1777", NeutralContent = "#FFFFFF",
                Base100 = "#FAF5FF", Base200 = "#EDE8F2", Base300 = "#DDD6FE", BaseContent = "#4C1D95",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["Newsletter"] = new ThemePalette
            {
                Primary = "#F97316", PrimaryFocus = "#C75C11", PrimaryContent = "#000000",
                Secondary = "#FB923C", SecondaryFocus = "#C87430", SecondaryContent = "#000000",
                Accent = "#1E293B", AccentFocus = "#18202F", AccentContent = "#FFFFFF",
                Neutral = "#1B2435", NeutralFocus = "#18202F", NeutralContent = "#FFFFFF",
                Base100 = "#FFFBEB", Base200 = "#F2EEDF", Base300 = "#FED7AA", BaseContent = "#1E293B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["DigitalProducts"] = new ThemePalette
            {
                Primary = "#8B5CF6", PrimaryFocus = "#6F49C4", PrimaryContent = "#FFFFFF",
                Secondary = "#A78BFA", SecondaryFocus = "#856FC8", SecondaryContent = "#000000",
                Accent = "#22C55E", AccentFocus = "#1B9D4B", AccentContent = "#000000",
                Neutral = "#441A86", NeutralFocus = "#3C1777", NeutralContent = "#FFFFFF",
                Base100 = "#FAF5FF", Base200 = "#EDE8F2", Base300 = "#DDD6FE", BaseContent = "#4C1D95",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["ChurchReligious"] = new ThemePalette
            {
                Primary = "#4C1D95", PrimaryFocus = "#3C1777", PrimaryContent = "#FFFFFF",
                Secondary = "#7C3AED", SecondaryFocus = "#632EBD", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#1B1843", NeutralFocus = "#18153C", NeutralContent = "#FFFFFF",
                Base100 = "#FAF5FF", Base200 = "#EDE8F2", Base300 = "#DDD6FE", BaseContent = "#1E1B4B",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SportsTeam"] = new ThemePalette
            {
                Primary = "#DC2626", PrimaryFocus = "#B01E1E", PrimaryContent = "#FFFFFF",
                Secondary = "#F87171", SecondaryFocus = "#C65A5A", SecondaryContent = "#000000",
                Accent = "#1E3A8A", AccentFocus = "#182E6E", AccentContent = "#FFFFFF",
                Neutral = "#721A1A", NeutralFocus = "#651717", NeutralContent = "#FFFFFF",
                Base100 = "#FEF2F2", Base200 = "#F1E5E5", Base300 = "#FECACA", BaseContent = "#7F1D1D",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["MuseumGallery"] = new ThemePalette
            {
                Primary = "#374151", PrimaryFocus = "#2C3440", PrimaryContent = "#FFFFFF",
                Secondary = "#6B7280", SecondaryFocus = "#555B66", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#0F1523", NeutralFocus = "#0D131F", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAFA", Base200 = "#EDEDED", Base300 = "#E5E7EB", BaseContent = "#111827",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["TheaterCinema"] = new ThemePalette
            {
                Primary = "#991B1B", PrimaryFocus = "#7A1515", PrimaryContent = "#FFFFFF",
                Secondary = "#DC2626", SecondaryFocus = "#B01E1E", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#E1E1E1", NeutralFocus = "#C8C8C8", NeutralContent = "#000000",
                Base100 = "#18181B", Base200 = "#232326", Base300 = "#3F3F46", BaseContent = "#FAFAFA",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["LanguageLearning"] = new ThemePalette
            {
                Primary = "#0D9488", PrimaryFocus = "#0A766C", PrimaryContent = "#FFFFFF",
                Secondary = "#2DD4BF", SecondaryFocus = "#24A998", SecondaryContent = "#000000",
                Accent = "#EA580C", AccentFocus = "#BB4609", AccentContent = "#FFFFFF",
                Neutral = "#114642", NeutralFocus = "#0F3E3B", NeutralContent = "#FFFFFF",
                Base100 = "#F0FDFA", Base200 = "#E4F0ED", Base300 = "#5EEAD4", BaseContent = "#134E4A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["CodingBootcamp"] = new ThemePalette
            {
                Primary = "#22C55E", PrimaryFocus = "#1B9D4B", PrimaryContent = "#000000",
                Secondary = "#4ADE80", SecondaryFocus = "#3BB166", SecondaryContent = "#000000",
                Accent = "#3B82F6", AccentFocus = "#2F68C4", AccentContent = "#FFFFFF",
                Neutral = "#D8DCE0", NeutralFocus = "#C0C4C7", NeutralContent = "#000000",
                Base100 = "#0F172A", Base200 = "#1B2234", Base300 = "#334155", BaseContent = "#F1F5F9",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["Cybersecurity"] = new ThemePalette
            {
                Primary = "#00FF41", PrimaryFocus = "#00CC34", PrimaryContent = "#000000",
                Secondary = "#0D0D0D", SecondaryFocus = "#0A0A0A", SecondaryContent = "#FFFFFF",
                Accent = "#00FF41", AccentFocus = "#00CC34", AccentContent = "#000000",
                Neutral = "#C9C9C9", NeutralFocus = "#B3B3B3", NeutralContent = "#000000",
                Base100 = "#000000", Base200 = "#0C0C0C", Base300 = "#1F1F1F", BaseContent = "#E0E0E0",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["DeveloperTool"] = new ThemePalette
            {
                Primary = "#3B82F6", PrimaryFocus = "#2F68C4", PrimaryContent = "#FFFFFF",
                Secondary = "#1E293B", SecondaryFocus = "#18202F", SecondaryContent = "#FFFFFF",
                Accent = "#2563EB", AccentFocus = "#1D4FBC", AccentContent = "#FFFFFF",
                Neutral = "#D8DCE0", NeutralFocus = "#C0C4C7", NeutralContent = "#000000",
                Base100 = "#0F172A", Base200 = "#1B2234", Base300 = "#334155", BaseContent = "#F1F5F9",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["Biotech"] = new ThemePalette
            {
                Primary = "#0EA5E9", PrimaryFocus = "#0B84BA", PrimaryContent = "#000000",
                Secondary = "#0284C7", SecondaryFocus = "#01699F", SecondaryContent = "#FFFFFF",
                Accent = "#10B981", AccentFocus = "#0C9467", AccentContent = "#000000",
                Neutral = "#0D1425", NeutralFocus = "#0C1221", NeutralContent = "#FFFFFF",
                Base100 = "#F8FAFC", Base200 = "#EBEDEF", Base300 = "#E2E8F0", BaseContent = "#0F172A",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SpaceTech"] = new ThemePalette
            {
                Primary = "#FFFFFF", PrimaryFocus = "#CCCCCC", PrimaryContent = "#000000",
                Secondary = "#94A3B8", SecondaryFocus = "#768293", SecondaryContent = "#000000",
                Accent = "#3B82F6", AccentFocus = "#2F68C4", AccentContent = "#FFFFFF",
                Neutral = "#DFE1E2", NeutralFocus = "#C6C8C9", NeutralContent = "#000000",
                Base100 = "#0B0B10", Base200 = "#17171B", Base300 = "#1E293B", BaseContent = "#F8FAFC",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["ArchitectureInterior"] = new ThemePalette
            {
                Primary = "#171717", PrimaryFocus = "#121212", PrimaryContent = "#FFFFFF",
                Secondary = "#404040", SecondaryFocus = "#333333", SecondaryContent = "#FFFFFF",
                Accent = "#D4AF37", AccentFocus = "#A98C2C", AccentContent = "#000000",
                Neutral = "#141414", NeutralFocus = "#121212", NeutralContent = "#FFFFFF",
                Base100 = "#FFFFFF", Base200 = "#F2F2F2", Base300 = "#E5E5E5", BaseContent = "#171717",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["QuantumComputing"] = new ThemePalette
            {
                Primary = "#00FFFF", PrimaryFocus = "#00CCCC", PrimaryContent = "#000000",
                Secondary = "#7B61FF", SecondaryFocus = "#624DCC", SecondaryContent = "#FFFFFF",
                Accent = "#FF00FF", AccentFocus = "#CC00CC", AccentContent = "#FFFFFF",
                Neutral = "#C9C9E5", NeutralFocus = "#B3B3CC", NeutralContent = "#000000",
                Base100 = "#050510", Base200 = "#11111B", Base300 = "#333344", BaseContent = "#E0E0FF",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["Biohacking"] = new ThemePalette
            {
                Primary = "#FF4D4D", PrimaryFocus = "#CC3D3D", PrimaryContent = "#000000",
                Secondary = "#4D94FF", SecondaryFocus = "#3D76CC", SecondaryContent = "#000000",
                Accent = "#00E676", AccentFocus = "#00B85E", AccentContent = "#000000",
                Neutral = "#19191B", NeutralFocus = "#161618", NeutralContent = "#FFFFFF",
                Base100 = "#F5F5F7", Base200 = "#E8E8EA", Base300 = "#E5E5EA", BaseContent = "#1C1C1E",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["AutonomousSystems"] = new ThemePalette
            {
                Primary = "#00FF41", PrimaryFocus = "#00CC34", PrimaryContent = "#000000",
                Secondary = "#008F11", SecondaryFocus = "#00720D", SecondaryContent = "#FFFFFF",
                Accent = "#FF3333", AccentFocus = "#CC2828", AccentContent = "#FFFFFF",
                Neutral = "#CFD5DA", NeutralFocus = "#B8BDC2", NeutralContent = "#000000",
                Base100 = "#0D1117", Base200 = "#191C22", Base300 = "#30363D", BaseContent = "#E6EDF3",
                Info = "#00BAFE", InfoContent = "#000000", Success = "#00D390", SuccessContent = "#000000",
                Warning = "#FCB700", WarningContent = "#000000", Error = "#FF627D", ErrorContent = "#000000"
            },
            ["GenerativeAIArt"] = new ThemePalette
            {
                Primary = "#111111", PrimaryFocus = "#0D0D0D", PrimaryContent = "#FFFFFF",
                Secondary = "#333333", SecondaryFocus = "#282828", SecondaryContent = "#FFFFFF",
                Accent = "#FFFFFF", AccentFocus = "#CCCCCC", AccentContent = "#000000",
                Neutral = "#000000", NeutralFocus = "#000000", NeutralContent = "#FFFFFF",
                Base100 = "#FAFAFA", Base200 = "#EDEDED", Base300 = "#E5E5E5", BaseContent = "#000000",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["SpatialVisionOS"] = new ThemePalette
            {
                Primary = "#FFFFFF", PrimaryFocus = "#CCCCCC", PrimaryContent = "#000000",
                Secondary = "#E5E5E5", SecondaryFocus = "#B7B7B7", SecondaryContent = "#000000",
                Accent = "#007AFF", AccentFocus = "#0061CC", AccentContent = "#FFFFFF",
                Neutral = "#000000", NeutralFocus = "#000000", NeutralContent = "#FFFFFF",
                Base100 = "#888888", Base200 = "#818181", Base300 = "#FFFFFF", BaseContent = "#000000",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
            ["ClimateTech"] = new ThemePalette
            {
                Primary = "#2E8B57", PrimaryFocus = "#246F45", PrimaryContent = "#FFFFFF",
                Secondary = "#87CEEB", SecondaryFocus = "#6CA4BC", SecondaryContent = "#000000",
                Accent = "#FFD700", AccentFocus = "#CCAC00", AccentContent = "#000000",
                Neutral = "#172D1C", NeutralFocus = "#142819", NeutralContent = "#FFFFFF",
                Base100 = "#F0FFF4", Base200 = "#E4F2E7", Base300 = "#C6E6C6", BaseContent = "#1A3320",
                Info = "#2563EB", InfoContent = "#FFFFFF", Success = "#16A34A", SuccessContent = "#FFFFFF",
                Warning = "#D97706", WarningContent = "#000000", Error = "#DC2626", ErrorContent = "#FFFFFF"
            },
        };

        /// <summary>
        /// Gets all available product palette names.
        /// </summary>
        public static IEnumerable<string> GetAllNames() => Palettes.Keys;

        /// <summary>
        /// Gets a pre-compiled ThemePalette by name.
        /// </summary>
        public static ThemePalette? Get(string name)
        {
            return Palettes.TryGetValue(name, out var palette) ? palette : null;
        }

        /// <summary>
        /// Checks if a product palette exists.
        /// </summary>
        public static bool Exists(string name) => Palettes.ContainsKey(name);
    }
}
